// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1-devel
// 	protoc        v3.11.2
// source: myProtobuf2.proto

package TripleGrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTripleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Group int32 `protobuf:"varint,1,opt,name=Group,proto3" json:"Group,omitempty"`
	Role  int32 `protobuf:"varint,2,opt,name=Role,proto3" json:"Role,omitempty"`
	Nlen  int32 `protobuf:"varint,3,opt,name=Nlen,proto3" json:"Nlen,omitempty"`
}

func (x *GetTripleRequest) Reset() {
	*x = GetTripleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_myProtobuf2_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTripleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTripleRequest) ProtoMessage() {}

func (x *GetTripleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_myProtobuf2_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTripleRequest.ProtoReflect.Descriptor instead.
func (*GetTripleRequest) Descriptor() ([]byte, []int) {
	return file_myProtobuf2_proto_rawDescGZIP(), []int{0}
}

func (x *GetTripleRequest) GetGroup() int32 {
	if x != nil {
		return x.Group
	}
	return 0
}

func (x *GetTripleRequest) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *GetTripleRequest) GetNlen() int32 {
	if x != nil {
		return x.Nlen
	}
	return 0
}

type GetBytesTripleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Group  int32 `protobuf:"varint,1,opt,name=Group,proto3" json:"Group,omitempty"`
	Role   int32 `protobuf:"varint,2,opt,name=Role,proto3" json:"Role,omitempty"`
	Length int32 `protobuf:"varint,3,opt,name=Length,proto3" json:"Length,omitempty"`
	Nlen   int32 `protobuf:"varint,4,opt,name=Nlen,proto3" json:"Nlen,omitempty"`
}

func (x *GetBytesTripleRequest) Reset() {
	*x = GetBytesTripleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_myProtobuf2_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBytesTripleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBytesTripleRequest) ProtoMessage() {}

func (x *GetBytesTripleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_myProtobuf2_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBytesTripleRequest.ProtoReflect.Descriptor instead.
func (*GetBytesTripleRequest) Descriptor() ([]byte, []int) {
	return file_myProtobuf2_proto_rawDescGZIP(), []int{1}
}

func (x *GetBytesTripleRequest) GetGroup() int32 {
	if x != nil {
		return x.Group
	}
	return 0
}

func (x *GetBytesTripleRequest) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *GetBytesTripleRequest) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *GetBytesTripleRequest) GetNlen() int32 {
	if x != nil {
		return x.Nlen
	}
	return 0
}

type Triple struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A int64 `protobuf:"varint,1,opt,name=A,proto3" json:"A,omitempty"`
	B int64 `protobuf:"varint,2,opt,name=B,proto3" json:"B,omitempty"`
	C int64 `protobuf:"varint,3,opt,name=C,proto3" json:"C,omitempty"`
}

func (x *Triple) Reset() {
	*x = Triple{}
	if protoimpl.UnsafeEnabled {
		mi := &file_myProtobuf2_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Triple) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Triple) ProtoMessage() {}

func (x *Triple) ProtoReflect() protoreflect.Message {
	mi := &file_myProtobuf2_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Triple.ProtoReflect.Descriptor instead.
func (*Triple) Descriptor() ([]byte, []int) {
	return file_myProtobuf2_proto_rawDescGZIP(), []int{2}
}

func (x *Triple) GetA() int64 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *Triple) GetB() int64 {
	if x != nil {
		return x.B
	}
	return 0
}

func (x *Triple) GetC() int64 {
	if x != nil {
		return x.C
	}
	return 0
}

type BitTriple struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A uint32 `protobuf:"varint,1,opt,name=A,proto3" json:"A,omitempty"`
	B uint32 `protobuf:"varint,2,opt,name=B,proto3" json:"B,omitempty"`
	C uint32 `protobuf:"varint,3,opt,name=C,proto3" json:"C,omitempty"`
}

func (x *BitTriple) Reset() {
	*x = BitTriple{}
	if protoimpl.UnsafeEnabled {
		mi := &file_myProtobuf2_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BitTriple) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BitTriple) ProtoMessage() {}

func (x *BitTriple) ProtoReflect() protoreflect.Message {
	mi := &file_myProtobuf2_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BitTriple.ProtoReflect.Descriptor instead.
func (*BitTriple) Descriptor() ([]byte, []int) {
	return file_myProtobuf2_proto_rawDescGZIP(), []int{3}
}

func (x *BitTriple) GetA() uint32 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *BitTriple) GetB() uint32 {
	if x != nil {
		return x.B
	}
	return 0
}

func (x *BitTriple) GetC() uint32 {
	if x != nil {
		return x.C
	}
	return 0
}

type BytesTrile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A []byte `protobuf:"bytes,1,opt,name=A,proto3" json:"A,omitempty"`
	B []byte `protobuf:"bytes,2,opt,name=B,proto3" json:"B,omitempty"`
	C []byte `protobuf:"bytes,3,opt,name=C,proto3" json:"C,omitempty"`
}

func (x *BytesTrile) Reset() {
	*x = BytesTrile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_myProtobuf2_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BytesTrile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BytesTrile) ProtoMessage() {}

func (x *BytesTrile) ProtoReflect() protoreflect.Message {
	mi := &file_myProtobuf2_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BytesTrile.ProtoReflect.Descriptor instead.
func (*BytesTrile) Descriptor() ([]byte, []int) {
	return file_myProtobuf2_proto_rawDescGZIP(), []int{4}
}

func (x *BytesTrile) GetA() []byte {
	if x != nil {
		return x.A
	}
	return nil
}

func (x *BytesTrile) GetB() []byte {
	if x != nil {
		return x.B
	}
	return nil
}

func (x *BytesTrile) GetC() []byte {
	if x != nil {
		return x.C
	}
	return nil
}

// Request message for getting a TripleList
type TripleList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Triple []*Triple `protobuf:"bytes,1,rep,name=triple,proto3" json:"triple,omitempty"`
}

func (x *TripleList) Reset() {
	*x = TripleList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_myProtobuf2_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TripleList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripleList) ProtoMessage() {}

func (x *TripleList) ProtoReflect() protoreflect.Message {
	mi := &file_myProtobuf2_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripleList.ProtoReflect.Descriptor instead.
func (*TripleList) Descriptor() ([]byte, []int) {
	return file_myProtobuf2_proto_rawDescGZIP(), []int{5}
}

func (x *TripleList) GetTriple() []*Triple {
	if x != nil {
		return x.Triple
	}
	return nil
}

type BitTripleList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bittriple []*BitTriple `protobuf:"bytes,1,rep,name=bittriple,proto3" json:"bittriple,omitempty"`
}

func (x *BitTripleList) Reset() {
	*x = BitTripleList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_myProtobuf2_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BitTripleList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BitTripleList) ProtoMessage() {}

func (x *BitTripleList) ProtoReflect() protoreflect.Message {
	mi := &file_myProtobuf2_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BitTripleList.ProtoReflect.Descriptor instead.
func (*BitTripleList) Descriptor() ([]byte, []int) {
	return file_myProtobuf2_proto_rawDescGZIP(), []int{6}
}

func (x *BitTripleList) GetBittriple() []*BitTriple {
	if x != nil {
		return x.Bittriple
	}
	return nil
}

type BytesTripleList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ByteTriple []*BytesTrile `protobuf:"bytes,1,rep,name=ByteTriple,proto3" json:"ByteTriple,omitempty"`
}

func (x *BytesTripleList) Reset() {
	*x = BytesTripleList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_myProtobuf2_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BytesTripleList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BytesTripleList) ProtoMessage() {}

func (x *BytesTripleList) ProtoReflect() protoreflect.Message {
	mi := &file_myProtobuf2_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BytesTripleList.ProtoReflect.Descriptor instead.
func (*BytesTripleList) Descriptor() ([]byte, []int) {
	return file_myProtobuf2_proto_rawDescGZIP(), []int{7}
}

func (x *BytesTripleList) GetByteTriple() []*BytesTrile {
	if x != nil {
		return x.ByteTriple
	}
	return nil
}

var File_myProtobuf2_proto protoreflect.FileDescriptor

var file_myProtobuf2_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6d, 0x79, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x32, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x54, 0x72, 0x69, 0x70, 0x6c, 0x65, 0x47, 0x72, 0x70, 0x63, 0x22,
	0x50, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x54, 0x72, 0x69, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x52, 0x6f, 0x6c,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x4e, 0x6c, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x4e, 0x6c, 0x65,
	0x6e, 0x22, 0x6d, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x42, 0x79, 0x74, 0x65, 0x73, 0x54, 0x72, 0x69,
	0x70, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x12, 0x12, 0x0a, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x52, 0x6f, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04,
	0x4e, 0x6c, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x4e, 0x6c, 0x65, 0x6e,
	0x22, 0x32, 0x0a, 0x06, 0x54, 0x72, 0x69, 0x70, 0x6c, 0x65, 0x12, 0x0c, 0x0a, 0x01, 0x41, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x41, 0x12, 0x0c, 0x0a, 0x01, 0x42, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x01, 0x42, 0x12, 0x0c, 0x0a, 0x01, 0x43, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x01, 0x43, 0x22, 0x35, 0x0a, 0x09, 0x42, 0x69, 0x74, 0x54, 0x72, 0x69, 0x70, 0x6c,
	0x65, 0x12, 0x0c, 0x0a, 0x01, 0x41, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x01, 0x41, 0x12,
	0x0c, 0x0a, 0x01, 0x42, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x01, 0x42, 0x12, 0x0c, 0x0a,
	0x01, 0x43, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x01, 0x43, 0x22, 0x36, 0x0a, 0x0a, 0x42,
	0x79, 0x74, 0x65, 0x73, 0x54, 0x72, 0x69, 0x6c, 0x65, 0x12, 0x0c, 0x0a, 0x01, 0x41, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x01, 0x41, 0x12, 0x0c, 0x0a, 0x01, 0x42, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x01, 0x42, 0x12, 0x0c, 0x0a, 0x01, 0x43, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x01, 0x43, 0x22, 0x38, 0x0a, 0x0a, 0x54, 0x72, 0x69, 0x70, 0x6c, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x2a, 0x0a, 0x06, 0x74, 0x72, 0x69, 0x70, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x54, 0x72, 0x69, 0x70, 0x6c, 0x65, 0x47, 0x72, 0x70, 0x63, 0x2e, 0x54,
	0x72, 0x69, 0x70, 0x6c, 0x65, 0x52, 0x06, 0x74, 0x72, 0x69, 0x70, 0x6c, 0x65, 0x22, 0x44, 0x0a,
	0x0d, 0x42, 0x69, 0x74, 0x54, 0x72, 0x69, 0x70, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x33,
	0x0a, 0x09, 0x62, 0x69, 0x74, 0x74, 0x72, 0x69, 0x70, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x54, 0x72, 0x69, 0x70, 0x6c, 0x65, 0x47, 0x72, 0x70, 0x63, 0x2e, 0x42,
	0x69, 0x74, 0x54, 0x72, 0x69, 0x70, 0x6c, 0x65, 0x52, 0x09, 0x62, 0x69, 0x74, 0x74, 0x72, 0x69,
	0x70, 0x6c, 0x65, 0x22, 0x49, 0x0a, 0x0f, 0x42, 0x79, 0x74, 0x65, 0x73, 0x54, 0x72, 0x69, 0x70,
	0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x0a, 0x42, 0x79, 0x74, 0x65, 0x54, 0x72,
	0x69, 0x70, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x54, 0x72, 0x69,
	0x70, 0x6c, 0x65, 0x47, 0x72, 0x70, 0x63, 0x2e, 0x42, 0x79, 0x74, 0x65, 0x73, 0x54, 0x72, 0x69,
	0x6c, 0x65, 0x52, 0x0a, 0x42, 0x79, 0x74, 0x65, 0x54, 0x72, 0x69, 0x70, 0x6c, 0x65, 0x32, 0xf2,
	0x01, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x54, 0x72, 0x69, 0x70, 0x6c, 0x65, 0x12, 0x46, 0x0a, 0x0c,
	0x47, 0x65, 0x74, 0x49, 0x6e, 0x74, 0x54, 0x72, 0x69, 0x70, 0x6c, 0x65, 0x12, 0x1c, 0x2e, 0x54,
	0x72, 0x69, 0x70, 0x6c, 0x65, 0x47, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x72, 0x69,
	0x70, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x54, 0x72, 0x69,
	0x70, 0x6c, 0x65, 0x47, 0x72, 0x70, 0x63, 0x2e, 0x54, 0x72, 0x69, 0x70, 0x6c, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x42, 0x69, 0x74, 0x54, 0x72,
	0x69, 0x70, 0x6c, 0x65, 0x12, 0x1c, 0x2e, 0x54, 0x72, 0x69, 0x70, 0x6c, 0x65, 0x47, 0x72, 0x70,
	0x63, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x72, 0x69, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x19, 0x2e, 0x54, 0x72, 0x69, 0x70, 0x6c, 0x65, 0x47, 0x72, 0x70, 0x63, 0x2e,
	0x42, 0x69, 0x74, 0x54, 0x72, 0x69, 0x70, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x00, 0x12,
	0x52, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x42, 0x79, 0x74, 0x65, 0x73, 0x54, 0x72, 0x69, 0x70, 0x6c,
	0x65, 0x12, 0x21, 0x2e, 0x54, 0x72, 0x69, 0x70, 0x6c, 0x65, 0x47, 0x72, 0x70, 0x63, 0x2e, 0x47,
	0x65, 0x74, 0x42, 0x79, 0x74, 0x65, 0x73, 0x54, 0x72, 0x69, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x54, 0x72, 0x69, 0x70, 0x6c, 0x65, 0x47, 0x72, 0x70,
	0x63, 0x2e, 0x42, 0x79, 0x74, 0x65, 0x73, 0x54, 0x72, 0x69, 0x70, 0x6c, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x22, 0x00, 0x42, 0x0e, 0x5a, 0x0c, 0x2f, 0x3b, 0x54, 0x72, 0x69, 0x70, 0x6c, 0x65, 0x47,
	0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_myProtobuf2_proto_rawDescOnce sync.Once
	file_myProtobuf2_proto_rawDescData = file_myProtobuf2_proto_rawDesc
)

func file_myProtobuf2_proto_rawDescGZIP() []byte {
	file_myProtobuf2_proto_rawDescOnce.Do(func() {
		file_myProtobuf2_proto_rawDescData = protoimpl.X.CompressGZIP(file_myProtobuf2_proto_rawDescData)
	})
	return file_myProtobuf2_proto_rawDescData
}

var file_myProtobuf2_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_myProtobuf2_proto_goTypes = []interface{}{
	(*GetTripleRequest)(nil),      // 0: TripleGrpc.GetTripleRequest
	(*GetBytesTripleRequest)(nil), // 1: TripleGrpc.GetBytesTripleRequest
	(*Triple)(nil),                // 2: TripleGrpc.Triple
	(*BitTriple)(nil),             // 3: TripleGrpc.BitTriple
	(*BytesTrile)(nil),            // 4: TripleGrpc.BytesTrile
	(*TripleList)(nil),            // 5: TripleGrpc.TripleList
	(*BitTripleList)(nil),         // 6: TripleGrpc.BitTripleList
	(*BytesTripleList)(nil),       // 7: TripleGrpc.BytesTripleList
}
var file_myProtobuf2_proto_depIdxs = []int32{
	2, // 0: TripleGrpc.TripleList.triple:type_name -> TripleGrpc.Triple
	3, // 1: TripleGrpc.BitTripleList.bittriple:type_name -> TripleGrpc.BitTriple
	4, // 2: TripleGrpc.BytesTripleList.ByteTriple:type_name -> TripleGrpc.BytesTrile
	0, // 3: TripleGrpc.GetTriple.GetIntTriple:input_type -> TripleGrpc.GetTripleRequest
	0, // 4: TripleGrpc.GetTriple.GetBitTriple:input_type -> TripleGrpc.GetTripleRequest
	1, // 5: TripleGrpc.GetTriple.GetBytesTriple:input_type -> TripleGrpc.GetBytesTripleRequest
	5, // 6: TripleGrpc.GetTriple.GetIntTriple:output_type -> TripleGrpc.TripleList
	6, // 7: TripleGrpc.GetTriple.GetBitTriple:output_type -> TripleGrpc.BitTripleList
	7, // 8: TripleGrpc.GetTriple.GetBytesTriple:output_type -> TripleGrpc.BytesTripleList
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_myProtobuf2_proto_init() }
func file_myProtobuf2_proto_init() {
	if File_myProtobuf2_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_myProtobuf2_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTripleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_myProtobuf2_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBytesTripleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_myProtobuf2_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Triple); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_myProtobuf2_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BitTriple); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_myProtobuf2_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BytesTrile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_myProtobuf2_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TripleList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_myProtobuf2_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BitTripleList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_myProtobuf2_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BytesTripleList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_myProtobuf2_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_myProtobuf2_proto_goTypes,
		DependencyIndexes: file_myProtobuf2_proto_depIdxs,
		MessageInfos:      file_myProtobuf2_proto_msgTypes,
	}.Build()
	File_myProtobuf2_proto = out.File
	file_myProtobuf2_proto_rawDesc = nil
	file_myProtobuf2_proto_goTypes = nil
	file_myProtobuf2_proto_depIdxs = nil
}
